### ISSUE TITLE
Замечания по 2 лабе

### ISSUE THREAD

**Issue by nightnoryu** [GsG-bOIIZ/hard-web#1]
1. Если шаблон `base.html.twig` не используется, лучше выпилить. Или разобраться и заиспользовать.
2. Для одного сервиса странное название `surveyServices`, как будто это аггрегация.

https://github.com/GsG-bOIIZ/hard-web/blob/8ba0dadeb25efb64c3d82ebd029fe174e1670ab2/lw2/SurveyApp/src/Controller/SurveyController.php#L12

3. Не хватает типов

https://github.com/GsG-bOIIZ/hard-web/blob/8ba0dadeb25efb64c3d82ebd029fe174e1670ab2/lw2/SurveyApp/src/Service/Survey/SurveyService.php#L10-L11

4. Эта перегонка из одного массива в другой по сути бесполезная

https://github.com/GsG-bOIIZ/hard-web/blob/8ba0dadeb25efb64c3d82ebd029fe174e1670ab2/lw2/SurveyApp/src/Controller/SurveyController.php#L15-L23

+ в контроллер так просачивается логика представления. Так же и в методе `viewSurvey`.

**Comment by GsG-bOIIZ** [comment]
Внес поправки

**Comment by nightnoryu** [comment]
1. Loader и FileStorage передаются через DI тут

https://github.com/GsG-bOIIZ/hard-web/blob/8a943bb3edfeafb7a3dac8835eb51f13e4d4bdb2/lw2/SurveyApp/src/Service/Survey/SurveyService.php#L14

Но потом все равно создаются вручную

https://github.com/GsG-bOIIZ/hard-web/blob/8a943bb3edfeafb7a3dac8835eb51f13e4d4bdb2/lw2/SurveyApp/src/Service/Survey/SurveyService.php#L16-L17

2. Лучше в контроллере заиспользовать DI и передавать `SurveyServiceInterface` через конструктор, а не в методах

**Comment by GsG-bOIIZ** [comment]
Внес поправки
1. ab1a62754e373dbefa9ca84ef97173dab1eeca56 
2. 2b4d64706d912a78dc13642304785e31338b55f1
